Update rtupdate

diff --git a/scripts/rtupdate b/scripts/rtupdate
--- a/scripts/rtupdate
+++ b/scripts/rtupdate
@@ -2,6 +2,8 @@
 
 ######################################################################
 #
+#  rtupdate - Updated for rtorrent 0.16.1 with libtorrent 0.13.8
+#  Based on working Ubuntu 24.04 configuration
 #  Copyright (c) 2015 arakasi72 (https://github.com/arakasi72)
 #
 #  --> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
@@ -10,190 +12,218 @@
 
 PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin
 
-osname=$(lsb_release -si)
-relno=$(lsb_release -sr | cut -d. -f1)
-fullrelno=$(lsb_release -sr)
+# CONFIRMED WORKING VERSIONS on Ubuntu 24.04
+# rtorrent 0.16.1 works with libtorrent 0.13.8 (NOT 0.14.0)
+DEFAULT_LIBVERS='0.13.8'
+DEFAULT_RTVERS='0.16.1'
 
-# Fallback if lsb_release -si returns nothing
-if [ "$osname" = "" ]; then
-  osname=$(grep -oP '(?<=^ID=).+' /etc/os-release | tr -d '"')
-  osname=${osname^}
-fi
-
-# Fallback if lsb_release -sr returns nothing
-if [ "$relno" = "" ]; then
-  relno=$(grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"' | cut -d. -f1)
-fi
-
-if [ "$fullrelno" = "" ]; then
-  fullrelno=$(grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"')
-fi
-
-
+# URLs
 sourcedir='https://rakshasa.github.io/rtorrent/'
 
-xmlrpc_url='https://svn.code.sf.net/p/xmlrpc-c/code/stable/'
-xmlrpcloc='svn://svn.code.sf.net/p/xmlrpc-c/code/stable/'
+# Parse arguments
+passed_rtvers="$1"
+libvers="$DEFAULT_LIBVERS"
+rtvers="$DEFAULT_RTVERS"
 
-xmlrpc_url_alt='https://github.com/mirror/xmlrpc-c'
-xmlrpcloc_alt='https://github.com/mirror/xmlrpc-c/trunk/stable'
+[ -z "$logfile" ] && logfile="/dev/null"
 
-rtdevrel=1
-
-libvers='0.13.8'
-rtvers='0.9.8'
-
-duoversion=''
-passed_rtvers=$1
-[ -z $logfile ] && logfile="/dev/null"
-
-
-# checks if an application is installed
+# Functions
 installed() {
-hash $1 2>/dev/null
+  hash "$1" 2>/dev/null
 }
 
-#function to check if a web site is reachable
 check_url() {
-  if [[ `wget -S -T 3 --spider $1  2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then return 0; else return 1; fi
+  if wget -S -T 3 --spider "$1" 2>&1 | grep -q 'HTTP/1.1 200 OK'; then
+    return 0
+  else
+    return 1
+  fi
 }
 
-
-ask_user(){
-local answer
-while true
-  do
-    read answer
-    case $answer in [Yy]* ) return 0 ;;
-                    [Nn]* ) return 1 ;;
-                        * ) echo "Enter y or n";;
+ask_user() {
+  local answer
+  while true; do
+    read -r answer
+    case "$answer" in
+      [Yy]* ) return 0 ;;
+      [Nn]* ) return 1 ;;
+      * ) echo "Enter y or n";;
     esac
   done
 }
 
+# Check running as root
 if [ "$(id -u)" != "0" ]; then
   echo "Must be run as root, or with sudo"
   exit 1
 fi
 
-# Check the libtorrent/rtorrent and xmlrpc sites are available
-xmlrpc_repo=0
+# Verify repositories are accessible
 rt_repo=0
+
 echo
 echo "Checking File Repositories"
-
-echo -n "xmlrpc-c: "; check_url $xmlrpc_url && echo "OK" ||  xmlrpc_repo=1
-
-if [[ $xmlrpc_repo = 1 ]]; then
-  xmlrpc_url=$xmlrpc_url_alt
-  xmlrpcloc=$xmlrpcloc_alt
-  check_url $xmlrpc_url && { echo "OK";  xmlrpc_repo=0; } || { echo "FAIL"; xmlrpc_repo=1; }
+echo -n "rtorrent: "
+if check_url "$sourcedir"; then
+  echo "OK"
+else
+  echo "FAIL"
+  rt_repo=1
 fi
 
-echo -n "rtorrent: "; check_url $sourcedir && echo "OK" || { echo "FAIL"; rt_repo=1; }
-
-if [ $rt_repo = 1 ]; then
-  echo "The libtorrent/rtorrent file repositoy is offline"
-  echo "Try again later, you can check if the following address is online in your browser:"
-  echo $sourcedir
+if [ "$rt_repo" -eq 1 ]; then
+  echo "ERROR: The rtorrent repository is offline"
+  echo "Check: $sourcedir"
   exit 1
 fi
 
-if [ $xmlrpc_repo = 1 ]; then
-  if [ -d /usr/include/xmlrpc-c ]; then
-    echo "xmlrpc repository is off line, but looks like it has already beed installed."
-    echo "We will try and install rtorrent"
-  else
-    echo "The xmlrpc-c file repositoy is offline"
-    echo "Try again later, you can check if the following address is online in your browser:"
-    echo $xmlrpcloc
-    exit 1
-  fi
+# Check if xmlrpc-c is already installed (Ubuntu 24.04 package works fine)
+if [ ! -d /usr/include/xmlrpc-c ]; then
+  echo "Installing xmlrpc-c from Ubuntu repositories"
+  aptitude -q=5 -y install libxmlrpc-core-c3-dev libxmlrpc-c++8-dev >> "$logfile" 2>&1
 fi
 
-if [ -z $passed_rtvers ]; then
-  if ( installed rtorrent ); then
-    rt_current=$(rtorrent -h | grep -om 1 "[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}")
-    echo "rtorrent $rt_current detected"
-    exit 1
-  else
-    echo "rtorrent NOT installed"
-    echo "This script is for upgrading/downgrading only, not for initial install"
-    exit 1
-  fi
+# Version handling
+if [ -n "$passed_rtvers" ]; then
+  rtvers="$passed_rtvers"
+  # libtorrent 0.13.8 is confirmed working with rtorrent 0.16.1
+  case "$rtvers" in
+    0.16.*) libvers="0.13.8" ;;
+    0.15.*) libvers="0.13.8" ;;
+    0.9.8) libvers="0.13.8" ;;
+    0.9.6) libvers="0.13.6" ;;
+    *) 
+      echo "WARNING: Unknown rtorrent version, using default libtorrent $DEFAULT_LIBVERS"
+      libvers="$DEFAULT_LIBVERS"
+      ;;
+  esac
 fi
 
+# Check current installation
+if installed rtorrent; then
+  rt_current="$(rtorrent -h 2>&1 | grep -om 1 "[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}")"
+  echo "Current rtorrent version: $rt_current"
+  
+  if [ "$rt_current" = "$rtvers" ]; then
+    echo "rtorrent $rtvers is already installed"
+    echo -n "Reinstall anyway? "
+    if ! ask_user; then
+      exit 0
+    fi
+  fi
+else
+  echo "rtorrent not currently installed"
+fi
 
+# Determine home directory
 if [ -z "$home" ]; then
-  home=$HOME
+  home="$HOME"
 fi
 
 echo
-echo "Installing libtorrent-$libvers/rtorrent-$rtvers"
+echo "Installing libtorrent-$libvers / rtorrent-$rtvers"
+echo "This combination is CONFIRMED WORKING on Ubuntu 24.04"
+echo
 
-cd $home
-
+# Create source directory
+cd "$home" || exit
 if [ -d source ]; then
-  cd source
+  cd source || exit
 else
-  mkdir source && cd source
-fi
-rm -rf xmlrpc libtorrent* rtorrent*
-
-echo "Fetching source files"
-
-#if [ $rtdevrel = 0 ]; then
-#  git clone -q -b feature-bind --single-branch https://github.com/rakshasa/libtorrent.git libtorrent-$libvers
-#  git clone -q -b feature-bind --single-branch https://github.com/rakshasa/rtorrent.git rtorrent-$rtvers
-#else
-  curl -LOJ# https://github.com/rakshasa/rtorrent-archive/raw/master/libtorrent-$libvers.tar.gz
-  tar -xzf libtorrent-$libvers.tar.gz
-  curl -LOJ# https://github.com/rakshasa/rtorrent-archive/raw/master/rtorrent-$rtvers.tar.gz
-  tar -xzf rtorrent-$rtvers.tar.gz
-#fi
-
-if [ $xmlrpc_repo = 0 ]; then
-  svn co $xmlrpcloc xmlrpc  >> $logfile 2>&1
-  if [ ! -e xmlrpc ]; then 
-    git clone $xmlrpc_url_alt xmlrpc >> $logfile 2>&1
-    cd xmlrpc/stable
-  else cd xmlrpc; fi
-
-  echo "Installing xmlrpc" | tee -a $logfile
-  ./configure --prefix=/usr --disable-cplusplus >> $logfile 2>&1
-  make -j$(nproc) >> $logfile 2>&1
-  make -s install >> $logfile 2>&1
-  cd $home/source
+  mkdir source && cd source || exit
 fi
 
-cd libtorrent-$libvers
-echo "Installing libtorrent" | tee -a $logfile
-./autogen.sh >> $logfile 2>&1
-if [ $osname = "Raspbian" ]; then
-  ./configure --prefix=/usr --disable-instrumentation >> $logfile 2>&1
+rm -rf libtorrent* rtorrent*
+
+echo "Fetching source files..."
+
+# Download libtorrent 0.13.8
+echo "Downloading libtorrent $libvers..."
+curl -LOJ# "https://github.com/rakshasa/rtorrent/releases/download/v$rtvers/libtorrent-$libvers.tar.gz" || {
+  echo "ERROR: Failed to download libtorrent"
+  exit 1
+}
+tar -xzf "libtorrent-$libvers.tar.gz"
+
+# Download rtorrent 0.16.1
+echo "Downloading rtorrent $rtvers..."
+curl -LOJ# "https://github.com/rakshasa/rtorrent/releases/download/v$rtvers/rtorrent-$rtvers.tar.gz" || {
+  echo "ERROR: Failed to download rtorrent"
+  exit 1
+}
+tar -xzf "rtorrent-$rtvers.tar.gz"
+
+# Build libtorrent
+cd "libtorrent-$libvers" || exit
+echo "Building libtorrent $libvers" | tee -a "$logfile"
+
+./autogen.sh >> "$logfile" 2>&1
+./configure --prefix=/usr >> "$logfile" 2>&1
+
+if ! make -j"$(nproc)" >> "$logfile" 2>&1; then
+  echo "ERROR: libtorrent build failed"
+  echo "Check $logfile for details"
+  exit 1
+fi
+
+make -s install >> "$logfile" 2>&1
+ldconfig
+
+echo "✓ libtorrent $libvers installed"
+
+# Build rtorrent
+cd "../rtorrent-$rtvers" || exit
+echo "Building rtorrent $rtvers" | tee -a "$logfile"
+
+./autogen.sh >> "$logfile" 2>&1
+./configure --prefix=/usr --with-xmlrpc-c --enable-ipv6 >> "$logfile" 2>&1
+
+if ! make -j"$(nproc)" >> "$logfile" 2>&1; then
+  echo "ERROR: rtorrent build failed"
+  echo "Check $logfile for details"
+  exit 1
+fi
+
+make -s install >> "$logfile" 2>&1
+ldconfig
+
+echo "✓ rtorrent $rtvers installed"
+
+# Verify installation
+if installed rtorrent; then
+  installed_version="$(rtorrent -h 2>&1 | grep -om 1 "[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}")"
+  echo
+  echo "=========================================="
+  echo "Installation successful!"
+  echo "rtorrent version: $installed_version"
+  echo "libtorrent version: $libvers"
+  echo "=========================================="
+  echo
+  echo "Verifying installation..."
+  echo "SCGI should be on port 5000:"
+  lsof -i :5000 2>/dev/null | grep rtorrent || echo "  (rtorrent not currently running)"
 else
-  ./configure --prefix=/usr >> $logfile 2>&1
+  echo "ERROR: rtorrent installation failed"
+  exit 1
 fi
-make -j$(nproc) >> $logfile 2>&1
-make -s install >> $logfile 2>&1
 
-cd ../rtorrent-$rtvers
-echo "Installing rtorrent" | tee -a $logfile
-./autogen.sh >> $logfile 2>&1
-./configure --prefix=/usr --with-xmlrpc-c --enable-ipv6 >> $logfile 2>&1
-make -j$(nproc) >> $logfile 2>&1
-make -s install >> $logfile 2>&1
-ldconfig >> $logfile 2>&1
-
-
+# Restart rtorrent for all users
 if [ -d /var/www/rutorrent/conf/users ]; then
-  cd /var/www/rutorrent/conf/users
-  user_list=*
-  for user in $user_list; do
-    if [ ! "$user" = '*' ]; then
-      echo "Restarting rtorrent for $user"
-      su $user -c 'rt restart >> /dev/null 2>&1'
+  echo
+  echo "Restarting rtorrent for all users..."
+  cd /var/www/rutorrent/conf/users || exit
+  user_list=(*)
+  
+  for user in "${user_list[@]}"; do
+    if [ "$user" != '*' ] && id "$user" &>/dev/null; then
+      echo "  Restarting rtorrent for $user..."
+      su "$user" -c 'rt restart' >> /dev/null 2>&1 || true
+      sleep 2
     fi
   done
-  echo
 fi
+
+echo
+echo "Update complete!"
+echo "Run 'rtorrent -h' to verify the installed version."
+echo "Check ruTorrent web interface to confirm SCGI connection."
